In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import illustris_python as il

basePath = "../data/tng-100-1/catalogues/"
groupCatPath = "C:/Users/auror/astrophysics/master/illustris-project/data/tng100-1/output"
subhaloFields = ["SubhaloMass", 'SubhaloMassType', "SubhaloMassInHalfRadType", "SubhaloHalfmassRadType", "SubhaloPos", "SubhaloVel", "SubhaloSpin"]

subhalos = il.groupcat.loadSubhalos(groupCatPath, 99, fields=subhaloFields)
df_subhalos = il.pandasformat.dict_to_pandas(subhalos)

stars = pd.read_pickle(basePath + "test_cat01.pkl")
print(stars["id"])


0    398110
1    398282
2    398549
3    399101
4    402979
5    405460
6    409358
7    413091
8    414050
9    424986
Name: id, dtype: int64


In [2]:
id_list = list(stars["id"])
print("Subhalo positions")
for i in range(len(id_list)):
    print(df_subhalos["SubhaloPos"][id_list[i]])
    print(stars["SubhaloPosX"][i], stars["SubhaloPosY"][i], stars["SubhaloPosZ"][i])

Subhalo positions
[49568.938 23258.623 32110.148]
49568.9702621202 23258.598287210774 32110.207681821314
[15988.368 53388.125 19328.84 ]
15988.339390205843 53388.12688203618 19328.838172084364
[55645.234 60724.305  8130.172]
55645.24431580044 60724.24347375384 8130.202068680517
[54104.15   28021.334   1730.8711]
54104.13655169781 28021.27311035912 1730.8518498203268
[71297.38  56630.11  51900.605]
71297.40489052846 56630.110103236024 51900.64958860955
[15836.398  68795.01    4246.0347]
15836.415077314128 68795.01967856116 4246.00144568551
[12663.26 56319.25 37649.77]
12663.27062593605 56319.23509779535 37649.75588615485
[21179.166   66397.21      265.99426]
21179.133441940867 66397.1544197073 266.03192949564965
[56405.26   24180.764    947.2747]
56405.244053767 24180.825630945154 947.2481332245402
[27865.707 58721.406 59402.12 ]
27865.764007708152 58721.42693619403 59402.16711232226


In [4]:
print("Subhalo velocities")
for i in range(len(id_list)):
    print(df_subhalos["SubhaloVel"][id_list[i]])
    print(stars["SubhaloVelX"][i], stars["SubhaloVelY"][i], stars["SubhaloVelZ"][i])

Subhalo velocities
[133.57335  -68.816216  40.36176 ]
133.57350038492004 -68.81685361154035 40.36288993951909
[-27.95371  -71.333595  63.67257 ]
-27.953560880785382 -71.33386989663833 63.67299186169781
[72.669876 35.293064 42.630684]
72.67077608109915 35.29090984663424 42.63369223504969
[202.67659 182.44392  83.93527]
202.67718567134267 182.4432690410048 83.93573371357603
[ -5.587112  72.77968  433.585   ]
-5.588078536626028 72.7792488246904 433.5847758087006
[ 532.58264   83.92157 -233.29956]
532.5841208431088 83.92295426749341 -233.29833940357395
[ -18.818027 -179.22438   241.37378 ]
-18.816994652071973 -179.22506622614884 241.37321773282798
[-482.53964   413.91574   -82.640564]
-482.5400107702277 413.91598646053296 -82.64058027637248
[ 66.56248 157.8692  190.31494]
66.56068777830959 157.86843314864518 190.31246732046168
[-169.58159   43.07278 -103.58237]
-169.580750801787 43.07373194929026 -103.58272293773604


In [5]:
print("Subhalo half mass radius")
for i in range(len(id_list)):
    print("GC", df_subhalos["SubhaloHalfmassRadStellar"][id_list[i]])
    print("Snapshot", stars["SubhaloHalfmassRadStellar"][i])

Subhalo half mass radius
GC 6.287621
Snapshot 6.290894553423335
GC 7.0684953
Snapshot 7.0683947771848405
GC 7.3634167
Snapshot 7.361208379655985
GC 7.8172245
Snapshot 7.817251604508204
GC 8.788133
Snapshot 8.790678129556007
GC 6.801729
Snapshot 6.801529775488056
GC 7.696094
Snapshot 7.698464676250775
GC 8.039131
Snapshot 8.041550551702164
GC 8.517873
Snapshot 8.524592471443025
GC 8.257167
Snapshot 8.256289169126847
