In [6]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import illustris_python as il

basePath = "../data/tng-100-1/catalogues/"
groupCatPath = "C:/Users/auror/astrophysics/master/illustris-project/data/tng100-1/output"
subhaloFields = ["SubhaloMass", 'SubhaloMassType', "SubhaloMassInHalfRadType", "SubhaloHalfmassRadType", "SubhaloPos", "SubhaloVel", "SubhaloSpin"]

subhalos = il.groupcat.loadSubhalos(groupCatPath, 99, fields=subhaloFields)
df_subhalos = il.pandasformat.dict_to_pandas(subhalos)

stars = pd.read_pickle(basePath + "test_cat_02.pkl")
print(stars["id"])


0    52618.0
1    60731.0
2    69507.0
3    76086.0
4    83280.0
Name: id, dtype: float64


In [7]:
id_list = list(stars["id"])
print("Subhalo positions")
for i in range(len(id_list)):
    print(df_subhalos["SubhaloPos"][id_list[i]])
    print(stars["SubhaloPosX"][i], stars["SubhaloPosY"][i], stars["SubhaloPosZ"][i])

[74659.33  18347.502 24016.389]
74659.30231606486 18347.52604958556 24016.42486846721
[18832.76   68248.68    2399.8157]
18832.781770785587 68248.73281279128 2399.8353528505418
[43440.1   38187.387 70194.56 ]
43440.115060139 38187.36843339067 70194.51385511916
[36771.992    937.5334 70503.445 ]
36771.98057884672 937.574047139254 70503.4659197319
[23867.799 33076.1   41411.195]
23867.918560123162 33076.11857327403 41411.14821781807


In [9]:
print("Subhalo velocities")
for i in range(len(id_list)):
    print(df_subhalos["SubhaloVel"][id_list[i]])
    print(stars["SubhaloVelocityX"][i], stars["SubhaloVelocityY"][i], stars["SubhaloVelocityZ"][i])

Subhalo velocities
[ 93.14602 305.90457 152.78827]
94.20912789719988 309.3848585551581 154.526035039799
[ 21.870102  21.780874 -40.56558 ]
21.758922261317263 21.66527504285486 -40.3543670298024
[ 30.629827 -96.97477  -68.274315]
30.527163277609155 -96.64024451637295 -68.0391617255964
[-220.56462   -91.032135   24.597898]
-217.83122308682422 -89.90226164518525 24.292518298060894
[-149.86743  322.27896  168.55688]
-148.83566239688983 320.06539288084133 167.4008473903134


In [11]:
print("Subhalo half mass radius")
for i in range(len(id_list)):
    print("GC", df_subhalos["SubhaloHalfmassRadStellar"][id_list[i]])
    print("Snapshot", stars["SubhaloHalfmassRadStellar"][i])

Subhalo half mass radius
GC 35.77964
Snapshot 40.3240053005604
GC 33.382057
Snapshot 38.89691617964376
GC 32.648647
Snapshot 49.812263056090465
GC 23.77969
Snapshot 23.405951963005236
GC 33.215683
Snapshot 37.604380347194756
